### ISSUE TITLE
cover images

### ISSUE THREAD

**Issue by i-bash** [i-bash/pg-dev2app#10]
Одним запросом не надо, пусть по одной едут.

Я не смотрел, как у тебя сделано, но внешне вижу так. Посылаю пустой запрос, выводится вся сотня книг и начинают потихоньку приезжать обложки. Я тут же тычу в самую первую книгу и попадаю на ее страницу, но на правой панели вижу, как продолжают сыпаться запросы картинок. По моим представлениям, в тот момент, когда я ушел со списка книг, остаток обложек подгружать уже не надо.

**Comment by i-bash** [comment]
Проблема двухуровневая :). Для подробной информации о книге нет отдельной функции, по крайней мере, в доке (ну или ткни носом), всё про книгу беру из списка, а для простоты и картинку тоже. Поэтому всегда дотаскиваю все картинки. То есть список и детали книги это физически одна страница с двумя панелями. А корзина - другая.

И к тому же вебсокет-постгрес клиент синхронный, мы ж как раз за это боролись. Чтобы он не блокировал всё остальное, даю ему цепочку заданий (промисов) типа: вытащить картинку - вывести её - вывести - вытащить... и оставляю работать.

Это всё не так сложно переделать, тогда заодно хочется понять: когда из корзины идём в список книг, он пустой. Это хорошо или не очень?

**Comment by egor-rogov** [comment]
> Для подробной информации о книге нет отдельной функции, по крайней мере, в доке

Нету. Логика такая, что текстовую информацию есть смысл передать сразу, чтобы можно было все отобразить, а картинки тяжелые, для них отдельная функция (картинку можно показать, когда она доедет).

> список и детали книги это физически одна страница с двумя панелями

Да, это тоже логично. Может и нет смысла это переделывать, пускай себе загружаются...
Давай пока притормозим эту задачу, может потом еще какие-то мысли придут.

> когда из корзины идём в список книг, он пустой. Это хорошо или не очень?

Пустой список не напрягает.
