### ISSUE TITLE
Лишняя книга

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#14]
Наблюдаю забавное поведение:
1. Пустой поисковый запрос, жмем "Найти", кликаем в первую книгу из списка.
2. Жмем "К списку книг"
3. Еще раз жмем "Найти".

При этом первая книга задваивается.

**Comment by i-bash** [comment]
Я заметил, но воспроизвести не смог, решил, что двоится в глазах. Оказывается, не только у меня :) Можно в книгу и не ходить, просто Найти ещё раз. Убрал заголовки, а очистку забыл подправить.
