### ISSUE TITLE
Rating visualization

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#15]
А можешь сделать, как, например, в Озоне: https://www.ozon.ru/context/detail/id/149717044/
Т. е. чтобы полоска была видна только сквозь звезды.
То, как сейчас - лучше чем просто полоска, но все еще не очень похоже.

**Comment by i-bash** [comment]
На странице книги - не проблема, там ширину можно сделать фиксированной, как в Озоне. А насчёт списка не уверен, попробую.

**Comment by egor-rogov** [comment]
Попробуй пожалуйста.
Это, к слову, не только у Озона, но и у Амазона, например.

**Comment by i-bash** [comment]
На обоих сайтах при визуализации округляют рейтинг до 0.5 и используют иконки звёзд с шагом 0.5 т.е есть например картинка "4.5 звезды". Если так пойдёт, могу сделать.

**Comment by egor-rogov** [comment]
Можно и так, а почему нельзя сделать полоску фиксированной ширины и сверху на нее положить картинку с прозрачными звездами на белом фоне?

**Comment by i-bash** [comment]
Готово
