### ISSUE TITLE
Servers list

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#18]
В списке серверов для подключения у нас пестрит localhost. Давай в `config.js` добавим словесное описание и будем выводить его + порт:

- основной сервер (5432)
- пул соединений (6432)
- реплика (5433)

**Comment by i-bash** [comment]
Порядок будет как написано? Сейчас 6432, 5432, 5433, по умолчанию берётся 1-й элемент списка.

**Comment by egor-rogov** [comment]
Не, порядок надо оставить как сейчас.
