### ISSUE TITLE
Right pane autoscroll

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#19]
Надо автоматически скроллить правую панельку вниз, чтобы в ней всегда был виден текущий запрос (ну или новые запросы вверх вставлять, но это наверное хуже).

**Comment by i-bash** [comment]
Было сделано на чистом CSS ради плавности, но не заметил, что в Firefox не работает. Пришлось вернуться на JS, теперь дёргается при большом потоке запросов, но зато работает стабильно.
