### ISSUE TITLE
Set retail price

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#21]
В админке при установке розничной цены:
- Для значения по умолчанию надо отпускную цену умножить на два.
- Заменить "С" на "Действует с".
- Формат даты и времени сейчас нечеловеческий (2020-06-10T15:51) и похоже значение по умолчанию берется в GMT+00. Календарик приделывать не надо, но хорошо бы вывести как "10.06.2020 18:51". И шрифт чуть крупнее, а то сейчас он меньше, чем подписи.

**Comment by i-bash** [comment]
> Для значения по умолчанию надо отпускную цену умножить на два.
То есть в расчёт добавить коэффициент 2?

> Формат даты и времени сейчас нечеловеческий 
Firefox, как оказалось, не поддерживает стандартный input type="datetime", могу сделать отдельно date и time, первый будет с календариком.

**Comment by egor-rogov** [comment]
> То есть в расчёт добавить коэффициент 2?

Только в этом месте. Ну то есть "стандартная" розничная цена в двойку больше закупочной.

> могу сделать отдельно date и time, первый будет с календариком.

Можно и так. Но имей в виду, что дату вряд ли кто-то будет править. В основном время.

**Comment by i-bash** [comment]
Сделал получше. Показываю для справки отпускную цену, иначе магазин может  прогореть. Календарь добавляется браузером, когда он видит type="date", а без этого не будет валидации. Формат даты и времени определяется настройками локали браузера или наследуется от ОС, если что, крутить надо там.
