### ISSUE TITLE
Statement origin

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#23]
В правой панельке выводится такое:
`web@127.0.0.1:5432 (8959)`
web понятно,
127.0.0.1 тоже, но наверное лучше localhost,
5432 - порт, но почему при подключении к баунсеру тоже выводится 5432?
(8959) - для понятности лучше выводить как (pid 8959)

**Comment by egor-rogov** [comment]
Весь смысл этой штуки в том, чтобы было понятно, куда именно и как приложение пульнуло запрос.
У сервера имеет смысл спрашивать только pid. Все остальное есть у приложения: пользователь известен, узел и порт известен (config.js).

**Comment by i-bash** [comment]
Ну мало ли, знать, куда баунсер отправил, тоже полезно. Переделал.

**Comment by egor-rogov** [comment]
Полезно, но не в нашем случае.
