### ISSUE TITLE
Trace

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#25]
Надо чуть поменять трассировку. Вместо public.trace() вызывать:
- В магазине - webapi.trace(auth_token). Если токена нет, передавать NULL.
- В админке - empapi.trace().

**Comment by i-bash** [comment]
А как будет выключаться трассировка?

**Comment by egor-rogov** [comment]
Как и сейчас - никак (: 
Ты вызываешь функцию в начале каждой транзакции, если установлен флаг. Если флаг не установлен - не вызываешь. А функции устанавливают параметры только на время транзакции.

**Comment by i-bash** [comment]
Тогда готово
