### ISSUE TITLE
Images - why so slow?

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#27]
Решил попробовать, сколько времени занимает прочитать все обложки. EXPLAIN ANALYZE какую-то ерунду показывает, пока не понял почему. Но вот так сделал, чтобы уж точно честно:
`COPY ( SELECT webapi.get_image(b.book_id) FROM books b ) TO ...`
Получается секунды полторы-две на все обложки.
Внимание, вопрос: почему в приложении обложки появляются так медленно? Что тормозит?

**Comment by i-bash** [comment]
Замер на стороне вебсокет-сервера показывает, что тормозит клиент. Сервер шлёт ответ на запрос через сотые доли секунды, а получает запрос на следующую обложку почти через полсекунды.

2020-06-22T14:05:30.632Z (2)  Received WS message: {"rid":15,"data":{"type":"exec","data":{"connection":0,"sql":"select to_json(f.*) from webapi.get_image (book_id=>$1) f","params":[6]}}}
pg-engine: connection 0, execing "select to_json(f.*) from webapi.get_image (book_id=>$1) f"

2020-06-22T14:05:30.674Z (2)  Sending WS message to client: {"rid":15,"data":{"command":"SELECT","rowCount":1,"oid":null,"rows":[{"to_json":"\\xffd8ffe000104...

2020-06-22T14:05:31.152Z (2)  Received WS message: {"rid":16,"data":{"type":"exec","data":{"connection":0,"sql":"select pg_backend_pid() pid, set_config('application_name','dev2app',true)","params":[]}}}
pg-engine: connection 0, execing "select pg_backend_pid() pid, set_config('application_name','dev2app',true)"

2020-06-22T14:05:31.153Z (2)  Sending WS message to client: {"rid":16,"data":{"command":"SELECT","rowCount":1,"oid":null,"rows":[{"pid":19776,"set_config":"d...

2020-06-22T14:05:31.187Z (2)  Received WS message: {"rid":17,"data":{"type":"exec","data":{"connection":0,"sql":"select to_json(f.*) from webapi.get_image (book_id=>$1) f","params":[7]}}}
pg-engine: connection 0, execing "select to_json(f.*) from webapi.get_image (book_id=>$1) f"

2020-06-22T14:05:31.258Z (2)  Sending WS message to client: {"rid":17,"data":{"command":"SELECT","rowCount":1,"oid":null,"rows":[{"to_json":"\\xffd8ffe000104...

**Comment by i-bash** [comment]
Если соединить логи клиента и сервера, то получаем такую картину. Самая большая задержка - при передаче картинки от вебсокет-сервера вебсокет-клиенту.

17:15:37.832 sending request #14 wspg-client.js:41:4
14:15:37.833 Received WS message: {"rid":14,"data":{"type":"exec","data":{"connection":0,"sql":"select pg_backend_pid() pid, set_config('application_name','dev2app',true)","params":[]}}}
pg-engine: connection 0, execing "select pg_backend_pid() pid, set_config('application_name','dev2app',true)"
14:15:37.834 Sending WS message to client: {"rid":14,"data":{"command":"SELECT","rowCount":1,"oid":null,"rows":[{"pid":19776,"set_config":"d...
17:15:37.860 got response on request #14 wspg-client.js:41:4


17:15:37.862 sending request #15 wspg-client.js:41:4
14:15:37.863 Received WS message: {"rid":15,"data":{"type":"exec","data":{"connection":0,"sql":"select to_json(f.*) from webapi.get_image (book_id=>$1) f","params":[6]}}}
pg-engine: connection 0, execing "select to_json(f.*) from webapi.get_image (book_id=>$1) f"
14:15:37.902 Sending WS message to client: {"rid":15,"data":{"command":"SELECT","rowCount":1,"oid":null,"rows":[{"to_json":"\\xffd8ffe000104...
17:15:37.950 got response on request #15 wspg-client.js:41:4

17:15:38.278 sending request #16 wspg-client.js:41:4
14:15:38.279 Received WS message: {"rid":16,"data":{"type":"exec","data":{"connection":0,"sql":"select pg_backend_pid() pid, set_config('application_name','dev2app',true)","params":[]}}}
pg-engine: connection 0, execing "select pg_backend_pid() pid, set_config('application_name','dev2app',true)"
14:15:38.280 Sending WS message to client: {"rid":16,"data":{"command":"SELECT","rowCount":1,"oid":null,"rows":[{"pid":19776,"set_config":"d...
17:15:38.307 got response on request #16 wspg-client.js:41:4

17:15:38.310 sending request #17 wspg-client.js:41:4
14:15:38.311 Received WS message: {"rid":17,"data":{"type":"exec","data":{"connection":0,"sql":"select to_json(f.*) from webapi.get_image (book_id=>$1) f","params":[7]}}}
pg-engine: connection 0, execing "select to_json(f.*) from webapi.get_image (book_id=>$1) f"
14:15:38.362 Sending WS message to client: {"rid":17,"data":{"command":"SELECT","rowCount":1,"oid":null,"rows":[{"to_json":"\\xffd8ffe000104...
17:15:38.414 got response on request #17

**Comment by i-bash** [comment]
Я поправил баг: из-за замыкания в лог сервера выводилось время установки соединения, а не текущее.

**Comment by i-bash** [comment]
Попробовал воткнуть другой модуль в качестве вебсокет-сервера (ws вместо websocket), он поддерживает сжатие сообщений, но эффекта никакого. Запретил фрагментацию сообщений (т.е. принудительно отправляю одним фреймом) - тоже без толку. Пока больше мыслей нет.

**Comment by egor-rogov** [comment]
Оно как бы не критично, но дает сильно неверное представление о скорости работы с bytea. Придется объяснять, что на самом деле не все так плохо, а этого, конечно, хотелось бы избежать.

А там пропускная способность получается небольшая или накладные расходы на передачу сообщения? Если, например, все обложки разом пересылать, легче не станет?

**Comment by i-bash** [comment]
Ну да, повод для оправданий лучше бы заранее исключить. Судя по тому, что запрет разбиения на фреймы ничего не дал, тормозит пропускная способность. У меня подозрение, что текстовое сообщение в процессе передачи несколько раз преобразуется, но пока руки не дошли разобраться. В websocket, к примеру, валидация UTF8-сообщений написана на C++, что как бы намекает на узкое место. Попробую тащить все картинки сразу.

**Comment by i-bash** [comment]
Запрашиваю все обложки одним запросом, который предполагает на стороне базы вместо webapi.get_image что-то вроде
`
CREATE OR REPLACE FUNCTION webapi.get_images(book_ids integer[])
 RETURNS table(book_id int,cover bytea)
 LANGUAGE sql
 STABLE
AS $function$
SELECT book_id,cover FROM books WHERE book_id = any(get_images.book_ids);
$function$
;
`
Мне кажется, так напрягает меньше. И вывожу в правую панель и в лог сервера время выполнения запроса, которое замеряю как время выполнения метода connection.query в NodeJS на сервере WS. У меня все картинки едут примерно полсекунды т.е. драйвер совсем не быстрый.

**Comment by egor-rogov** [comment]
Не, ну полсекунды - это уже норм. Давай тогда на такой вариант перейдем?

**Comment by i-bash** [comment]
Полсекунды - это время на сервере WS. В браузере между отображением списка и показом картинок проходит секунды три.

**Comment by i-bash** [comment]
Ну в общем получилось сократить время между отправкой запроса и отображением картинок до 2 секунд. Сейчас расклад такой:
- полсекунды на запрос к Постгресу через драйвер
- полсекунды на пересылку данных в браузер
- секунда на преобразование 16-ричной строки в урл и запихивание его в атрибут элемента страницы <img src="data:image/jpeg;base64, ...">

Предлагаю перейти на этот  вариант, он явно лучше предыдущего. Нужно будет заменить get_image на get_images, надеюсь, это ничему не противоречит.

**Comment by egor-rogov** [comment]
В принципе я не против.

Но вот в порядке творческого бреда. Что, если тебе на клиенте открывать курсор для запроса
```sql
SELECT book_id, get_image(book_id) FROM books WHERE book_id = ANY(массив-id-шников);
```
тянуть из него строчки-обложки по одной и отрисовывать?
Это ведь тот же один запрос в базу, но зато картинки могут появляться постепенно. Но я, правда, толком не понял, что именно там тормозит.

**Comment by i-bash** [comment]
Оно везде тормозит понемногу. Самое узкое место было при преобразовании 16-ричной строки bytea в урл "data:image/jpeg;base64, ...". Я делал это с помощью строковых функций JS, а сейчас использовал объекты Blob и FileReader, стало побыстрее. Вернулся к вытаскиванию каждой картинки отдельным запросом, посмотри. Курсор, думаю, особо ничего не даст, зато придётся усложнить вебсокет-сервер.

**Comment by egor-rogov** [comment]
Посмотрел - вроде пошустрее стало. А вариант с `get_images` быстрее работал (я его не видел)?

**Comment by i-bash** [comment]
Субъективно картинки одним запросом работали чуть быстрее: на 2 секунды всё замирало и потом показывались сразу все. Но по одной, мне кажется, веселее. Задержки в основном из-за последовательных вызовов: пока картинка не отобразится, следующий запрос не отправляется. Можно ещё поработать с параллельностью, сериализовать только запросы через вебсокет.

**Comment by egor-rogov** [comment]
Если не сильно напряжно, то было бы интересно попробовать такой вариант. Наверняка должно хорошо ускориться.

**Comment by i-bash** [comment]
Удивительно, но кардинально быстрее не стало. Теперь узкое место - пересылка ответов от сервера через сокет. При отправке серии команд любое сообщение от вебсокет-сервера, начиная со второго, идёт в браузер довольно долго: от 150 мс для коротких (инфа о соединении) до 300 мс (обложка). Решил всё же выложить текущий вариант. Покопаюсь ещё, но похоже, что надо уже лезть вглубь сервера.

**Comment by egor-rogov** [comment]
К концу притормаживает, а в начале так совсем красота.

**Comment by i-bash** [comment]
Здесь хорошо видно, что происходит. На картинке - последние запросы серии, первое время замеряю на сервере вебсокета = клиенте БД, второе - в браузере. Почти нулевой результат запроса (backend pid), идёт через сокет 100+ мс.
![image](https://user-images.githubusercontent.com/6612287/86773403-4ed0ff80-c05e-11ea-8e23-c4d385644b7b.png)
Я подчистил передаваемые данные, чтобы уменьшить объём, исправил пару мелких багов и предлагаю на этом остановиться, если ты не против. Технические запросы показывать не буду, время выполнения запроса к БД (первое) наверное будет полезно.

**Comment by egor-rogov** [comment]
Ага, давай остановимся на достигнутом.
Разделить время на БД и приложение - весьма полезно, оставляй две циферки!
