### ISSUE TITLE
Order by layout broken

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#28]
Что-то у меня после обновления стрелки "по убыванию/по возрастанию" съехали вниз. От ширины экрана не зависит.

![Screenshot_2020-07-08_12-23-59](https://user-images.githubusercontent.com/12832436/86902311-75527180-c116-11ea-975b-5f2845471844.png)

**Comment by i-bash** [comment]
Эх, не проверил на 32-битных пикселях, а они оказались толще :) на самом деле шрифт по умолчанию другой.
