### ISSUE TITLE
Locale of the calendar

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#29]
В админке в "окошке" установки цены дата отображается в виде `07 / 10 / 2020`, и названия месяцев и дней недели на английском.
В виртуалке `LC_TIME=ru_RU.UTF-8`.
Не критично, но если можно поменять локаль календаря, то было бы хорошо.

**Comment by egor-rogov** [comment]
А, и еще время там в формате AM/PM. То есть у меня 13:17, а вижу 01:17.

**Comment by i-bash** [comment]
Правильнее поменять язык в браузере, но тогда меню будет на русском.

**Comment by egor-rogov** [comment]
Меня на русском - бее...
Если бы не кривое время, с датой можно было бы и смириться.

**Comment by i-bash** [comment]
Подёргал галочки в настройках браузера, и всё заработало как надо. В результате в prefs.js добавилась строка
````user_pref("intl.regional_prefs.use_os_locales", true);````
Только надо как-то угадать имя профиля, у меня полный путь к файлу
````.mozilla/firefox/dagh8u88.default-release/prefs.js````

**Comment by egor-rogov** [comment]
У меня другой путь, естественно. Лучше в ручные действия пропишу.
А какие галочки-то ставил? Я что-то сходу не нашел.

**Comment by i-bash** [comment]
![image](https://user-images.githubusercontent.com/6612287/87182025-ff9ffe80-c2eb-11ea-975b-d22b04ed7feb.png)
Галочка здесь, но сначала её не было, а потом появилась в результате каких-то действий. Добавлял русский язык как альтернативный, менял порядок языков для интерфейса, вызывал браузер из командной строки -- что-то из этого.

**Comment by i-bash** [comment]
Получилось?

**Comment by i-bash** [comment]
> У меня другой путь, естественно. Лучше в ручные действия пропишу.
> А какие галочки-то ставил? Я что-то сходу не нашел.
Директория с профилем всегда будет *.default-release, и она единственная.

**Comment by egor-rogov** [comment]
Ну вот у меня она оказалась .default, без release.
Придумаю что-нибудь, не проблема. Спасибо!

**Comment by egor-rogov** [comment]
about:config нас спасет (:
