### ISSUE TITLE
Date & time format for background tasks

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#33]
В окошке фоновых заданий дата и время начала и окончания выводятся в странном формате. Хотелось бы нечто стандартное, например всегда DD.MM.YYYY HH24:MI:SS

![Screenshot_2020-08-03_21-53-57](https://user-images.githubusercontent.com/12832436/89216889-e8df8580-d5d3-11ea-827c-b2cb24c09837.png)

**Comment by i-bash** [comment]
В сети дискутируют, баг это или фича, прописал явно локаль из настроек браузера. Сейчас часто для последних суток показывают только время, а для более старых моментов - только дату, чтобы сэкономить ширину. Но здесь вроде ширины хватает, так что вывожу и дату, и время.

**Comment by egor-rogov** [comment]
А формат даты по-прежнему нестандартный: "8/18/2020, 5:03:31 PM".

**Comment by i-bash** [comment]
![image](https://user-images.githubusercontent.com/6612287/90649962-ede33c80-e243-11ea-9d83-ae3868f18e63.png)

**Comment by egor-rogov** [comment]
Типа от локали зависит? Или поправил?

**Comment by i-bash** [comment]
Ничего не правил, сделал git pull в виртуалке.
null
