### ISSUE TITLE
Layout of background tasks

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev2app#34]
Есть соображения насчет внешнего вида окошка фоновых заданий. Сейчас оно выглядит несколько "непричесаным".
Предложение такое.

```
[ --- выбор программы --- ]   [ Выполнить ]

(.) Локально                             [ --- окошко         ]
( ) Удаленно [ --- выбор сервера --- ]   [     параметров --- ]
```

То есть:
* Вместо чекбокса предлагаю сделать радиокнопку - кажется так понятнее.
* Выбор удаленного сервера должен выглядеть точно так же, как в информационной панели. И скрывать его в таком варианте не надо.
* Окошко параметров не подписывать, а сделать `<textarea placeholder="параметры (json)">`. По умолчанию пусть NULL в табличку записывается.

Еще: кнопку обновления хотелось бы сделать побольше-позаметнее. Может, просто написать на ней "Обновить"?

**Comment by i-bash** [comment]
Сделал чуть по-другому, так лучше адаптируется к разным экранам.

**Comment by egor-rogov** [comment]
Что-то я не в восторге...

![Screenshot_2020-08-18_17-13-39](https://user-images.githubusercontent.com/12832436/90524202-73002000-e176-11ea-8e65-e64ab6576cab.png)

1. Между выбором задания и кнопкой Выполнить находятся поля, с которых я наоборот хотел убрать акцент. Чтобы был визуально короткий путь "выбрал - выполнил".
2. При небольшом уменьшении шириниы кнопка Выполнить съезжает вниз (как на скриншоте).
3. Неестественный размер элемента для выбора задания режет глаз. А серый цыет фона еще больше.
4. Поломалась логика: сейчас при локальном запуске в порт вместо null передается 0 (см. инфопанель на скриншоте).

Есть предложение все-таки попробовать сверстать так, как я предлагал, и
а) заменить цвет фона в select-е с серого на белый (как было раньше);
б) уменьшить высоту textarea до двух строк;
в) починить null.

**Comment by i-bash** [comment]
Всё поправил, можно придираться :)

**Comment by egor-rogov** [comment]
Почти идеально (:
А можешь сделать так, чтобы длина select-а выбора задания была точно равна длине нижележащих radiobutton + textarea? И на этом, пожалуй, надо уже остановиться.

**Comment by i-bash** [comment]
Конечно могу, я специально это оставил для придирок :)
Если серьёзно, там сейчас ширина элементов зависит от ширины экрана, и наверное это не очень хорошо, переделаю.

**Comment by egor-rogov** [comment]
Правильно, очень важно заготовить повод для придирки, чтобы все остались довольны (:

**Comment by i-bash** [comment]
Ну как-то так. Можно ещё придираться.

**Comment by egor-rogov** [comment]
Супер, берём.
