### ISSUE TITLE
rating

### ISSUE THREAD

**Issue by i-bash** [i-bash/pg-dev2app#9]
Можно ж и не округлять. Я б сделал картинку с 5-ю прозрачными звездами на белом фоне, а под ними растягивал на нужную ширину картинку из одного желтого пикселя (хотя может желтую полоску и css-ом можно нарисовать).

**Comment by i-bash** [comment]
Сделал css-ом. Сейчас просто жёлтая полоска, стоит туда ещё звёзды присобачить?

**Comment by egor-rogov** [comment]
> стоит туда ещё звёзды присобачить?

Да, полоска не читается как рейтинг.
